# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  #config.vm.network :hostonly, "33.33.33.99"

  # Necessary for homesick_agent::data_bag
  #config.ssh.forward_agent = true

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.host_key_checking = false
  end
end
